---
- name: Create localtmp if not exists
  hosts: all
  gather_facts: false
  tasks:

  - name: Check if /local exists
    stat:
      path: /local
    register: stat_result

  - name: Create the file, if it doesnt exist already
    file:
      path: /local/tmp
      state: directory
      owner: root
      group: root
      mode: '1777'
    when: stat_result.stat.exists == True

  - name: Ansible delete file glob
    find:
      paths: /local/tmp
      patterns: hdx.*
    register: files_to_delete

  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
